uses: actions/setup-java@v3
  with:
    distribution: 'zulu'
    java-version: "12.x"
    cache: 'gradle' // 1

  - uses: subosito/flutter-action@v2
    with:
      flutter-version: "3.0.0"
      channel: 'stable'
      cache: true // 2